# å¿…è¦æ¥ç¶šåˆ†æ•°
required_time = 10

# ã‚µãƒ¼ãƒãƒ¼ID
guild_id = "0000000000000000000"

# ã‚¢ãƒŠã‚¦ãƒ³ã‚¹ãƒãƒ£ãƒ³ãƒãƒ«ID
announcement_channel_id = "0000000000000000000"

# ã‚¢ãƒŠã‚¦ãƒ³ã‚¹ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸
announcement_message = "<@&0000000000000000000> {event} ã‚¤ãƒ™ãƒ³ãƒˆãŒå§‹ã¾ã‚Šã¾ã™ï½ï¼"

# ã‚¢ãƒŠã‚¦ãƒ³ã‚¹æ‹›å¾…ãƒªãƒ³ã‚¯ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸
announcement_invite_link_message = "{vc} ã¸ã„ã‚‰ã£ã—ã‚ƒã„ï½"

# ã‚¢ãƒŠã‚¦ãƒ³ã‚¹ãƒ­ãƒ¼ãƒ«ID
announcement_role_id = "0000000000000000000"

# ã‚¤ãƒ™ãƒ³ãƒˆäºˆå®šãƒãƒ£ãƒ³ãƒãƒ«ID
schedule_channel_id = "0000000000000000000"

# ã‚¤ãƒ™ãƒ³ãƒˆå‚åŠ æ¸ˆãƒ­ãƒ¼ãƒ«ã®ID
event_join_role_id = "0000000000000000000"

# ã‚¤ãƒ™ãƒ³ãƒˆæ“ä½œãƒãƒ£ãƒ³ãƒãƒ«ID
event_panel_channel_id = "0000000000000000000"

# ã‚¤ãƒ™ãƒ³ãƒˆé€£çµ¡ãƒãƒ£ãƒ³ãƒãƒ«ID
event_contact_channel_id = "0000000000000000000"

# æœ¬æ—¥ã®ä¸»å‚¬è€…ãƒ­ãƒ¼ãƒ«ID
host_role_id = "0000000000000000000"

# ãƒªãƒã‚¤ãƒ³ãƒ‰ç®¡ç†è€…ãƒ­ãƒ¼ãƒ«ID
remind_admin_role_id = "0000000000000000000"

# ãƒ†ã‚­ã‚¹ãƒˆã‚¤ãƒ™ãƒ³ãƒˆç”¨ã®ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆãƒãƒ£ãƒ³ãƒãƒ«ID
text_event_channel_id = "0000000000000000000"

# ã‚¤ãƒ™ãƒ³ãƒˆãƒãƒŠãƒ¼ç”»åƒURLï¼ˆã‚ªãƒ—ã‚·ãƒ§ãƒ³ï¼‰
# event_banner_url = "https://example.com/banner.png"

# æœ€è¿‘ã‚¤ãƒ™ãƒ³ãƒˆã«å‚åŠ ã—ãŸãƒ­ãƒ¼ãƒ«ã®ID { ãƒ­ãƒ¼ãƒ«ID = å¿…è¦å›æ•° }
[recent_event_join_role_ids]
"0000000000000000000" = 1
"0000000000000000000" = 4

# çµµæ–‡å­—ãƒªã‚¹ãƒˆ
[emojis]
"ãƒã‚¤ã‚¯ãƒ©" = "<:minecraft:1259327155418955858>"
"ã‚¢ã‚¯ãƒ†ã‚£ãƒ“ãƒ†ã‚£" = "ğŸš€"
"Gartic" = "â˜ï¸"
"bonk" = "ğŸ"
"ã‚¹ãƒ—ãƒ©" = "<:splatoon:1123608480071303199>"
"GodField" = "<:goffi:1123607123541110825>"
"tetr.io" = "<:tetrio:1130332939616530472>"
"Among" = "<:amongus:1123607314864275506>"
"ãƒãƒ¼ã‚«ãƒ¼" = "â™ ï¸"
"ã‚¸ã‚ªã‚²ãƒƒã‚µãƒ¼" = "<:geoguessr:1123607393666875462>"
"ãƒãƒªã‚ª" = "<:mario:1307575100471509055>"
"ã‚¹ãƒãƒƒã‚·ãƒ¥ãƒ–ãƒ©ã‚¶ãƒ¼ã‚º" = "<:smashbros:1123608751333707918>"
"Overwatch" = "<:overwatch:1125772179032772688>"
"ãƒœãƒ¼ãƒ‰ã‚²ãƒ¼ãƒ " = "<:bga:1180936274627014707>"
"VALORANT" = "<:valorant:1123607231531847740>"
"Overcooked" = "<:overcooked:1123608690256252948>"
"TITANS" = "<:PAT:1160190345645133865>"
"ãƒãƒªã‚ªã‚«ãƒ¼ãƒˆ" = "<:mariokart:1125770776788877384>"
"PICO" = "<:picopark:1307576853984313404>"
"ä¼šè­°" = "ğŸ“"
"å®šä¾‹ä¼š" = "ğŸ“…"
"æŠ€è¡“é›‘è«‡" = "ğŸ”§"
"Codenames" = "ğŸ•µï¸"
"ãƒã‚§ã‚¹" = "â™Ÿï¸"
"æ–°è¦" = "ğŸ¥³"
